project2/config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :users do
    resources :posts do
      resources :comments, only: [:create]
    end
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'

end

project2/app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :post
  belongs_to :user

end

project2/app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  has_many :comments, dependent: :destroy

end

project2/app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  has_many :posts
  has_many :comments

  # validates: :email, presence: true
  # validates: :email, email_format: {message: "wrong email, yo"}
  # validates: :password, length: {in: 6..20}
  # validates: :password_confirmation, presence: true

end

project2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Method to look up the user, if they're logged in, and save their user object to a variable called @current_user.
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  # The helper_method below the method current_user allows us to use @current_user in our view files.
  helper_method :current_user

  # Authorize is for sending someone to the login page if they aren't logged in
  def authorize
    redirect_to '/login' unless current_user
  end

end

project2/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]
    @comment.save
    redirect_to post_path(@comment.post)
  end

  private

  def comment_params
    params.require(:comment).permit(
    :text,
    :image_url
    )
  end

end

project2/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :show, :update, :destroy]

  def index
    #@posts = Post.all
    @posts = User.find(params[:user_id]).posts
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to user_posts_path(@post.user_id)
    else
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to user_posts_path(@post.user_id)
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to user_posts_path(@post.user_id)
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(
    :text,
    :image_url
    )
  end
end

project2/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
   # If the user exists AND the password entered is correct.
   if user && user.authenticate(params[:password])
     # Save the user id inside the browser cookie. This is how we keep the user
     # logged in when they navigate around our website.
     session[:user_id] = user.id
     redirect_to user_path(user)
   else
   # If user's login doesn't work, send them back to the login form.
     redirect_to '/login'
   end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

project2/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize, except: [:new, :create]

  def index
    @users = User.all
  end

  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/users'
    else
      redirect_to '/signup'
    end
  end

  def show
  end

  def edit
    #@user = User.find(params[:id])
  end

  def update
    id = params[:id]
    user = User.find(id)

    if user.update(user_params)
      redirect_to('/users')
    else
      redirect_to "users/#{current_user.id}/edit/"
    end
  end

  private

  def user_params
    params.require(:user).permit(
    :alias,
    :email,
    :password,
    :password_confirmation
    )
  end

end

project2/app/helpers/application_helper.rb
module ApplicationHelper
end

project2/app/views/comments/form.html.erb
<h3>
  Post A Comment
</h3>
<%= form_for [@post, @comment] do |t| %>
  <p>
    <%= t.label :content %>
      <br>
    <%= t.text_field :content %>
  </p>
  <p>
    <%= t.submit "Add New Comment", class: "button" %>
  </p>
<% end %>

project2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
    Signed in as <%= current_user.alias %> | <%= link_to "Logout", '/logout' %>
  <% else %>
    <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
  <% end %>

<%= yield %>

</body>
</html>

project2/app/views/posts/_comment.html.erb
<div>
  <p>
    <%= comment.content %>
  </p>
</div>

project2/app/views/posts/_form.html.erb
<%= form_for(@post, url: user_posts_path(current_user)) do |f| %>
  <p>
    <%= f.label :text %>
    <%= f.text_area :text, size: "30x3" %>
    <img src="<%= @post.image_url %>" alt= "<%= @post.id %>" >
    <%= f.label "Image" %>
    <%= f.text_field :image_url %>
    <%= f.submit class: "button" %>
  </p>
<% end %>

project2/app/views/posts/edit.html.erb
<h1>
  Edit Post
</h1>
<%#= render partial: 'form' %>
<%= form_for @post, url: {action: "update"} do |f| %>
  <p>
    <%= f.label :text %>
    <%= f.text_area :text, size: "30x3" %>
    <img src="<%= @post.image_url %>" alt= "<%= @post.id %>" >
    <%= f.label "Image" %>
    <%= f.text_field :image_url %>
    <%= f.submit class: "button" %>
  </p>
<% end %>
<h4>
<%= link_to "Return to User's Posts", "/users/#{current_user.id}/posts" %>
</h4>

project2/app/views/posts/index.html.erb
<h3>
  Posts by <%= "#{current_user.alias}" %>
</h3>
<% @posts.each do |post| %>
    <div class="post">
      <%= link_to post.text, user_posts_path(post.user.id) %>
      <img src="<%= post.image_url %>" alt="<%= post.id %>" />
      <%= link_to "Edit", edit_user_post_path(post.user.id, post.id), class: "button" %>
      <%= link_to "Delete", user_post_path(post.user.id, post.id), method: :delete, class: "button danger" %>
    </div>
  <% end %>
<h4>
<%= link_to "Return to User Profile", "/users/#{current_user.id}" %>
</h4>

project2/app/views/posts/new.html.erb
<h1>
  Add A New Post
</h1>
<%= render partial: 'form', locals: {post: @post, user: current_user.id} %>
<h4>
<%= link_to "Return to User Profile", "/users/#{current_user.id}" %>
</h4>

project2/app/views/posts/show.html.erb
<h2>
  <%= @post.content %>
</h2>
<img src="<%= @post.image_url %>" alt="<%= @post.id %>" />
<%= render partial: 'comments/form' %>
<h3>
  Comments
</h3>
<%= render partial: 'posts/comment', collection: @post.comments %>
<%= link_to "Edit", edit_post_path(@post), class: "button" %>
<%= link_to "Delete", post_path(@post), class: "button danger" %>
<%= link_to "Return to Posts", posts_path, class: "button" %>

project2/app/views/users/edit.html.erb
<%= form_for current_user do |f| %>
  Alias: <%= f.text_field :alias %>
  Email: <%= f.text_field :email %>
  <%= f.submit "Submit Change" %>
<% end %>
<h4>
<%= link_to "Return to User Profile", "/users/#{current_user.id}" %>
</h4>

project2/app/views/users/index.html.erb
<h1>
  Current User List Below
</h1>
  <ul>
    <% @users.each do |user| %>
    <li>
      User ID: <%= user.id %>
      Alias: <%= user.alias %>
      Email: <%= user.email %>
    </li>
    <% end %>
  </ul>
<h4>
  <%= link_to "Return to User Profile", "/users/#{current_user.id}" %>
</h4>

project2/app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  Alias: <%= f.text_field :alias %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>

project2/app/views/users/show.html.erb
<h1>User Profile</h1>

<%= current_user.alias %>
<%= current_user.email %>

<h2>
  Create A Post
</h2>
<h4>
<%= link_to "Create Post", new_user_post_path(current_user) %>
</h4>
<h2>
  List of User's Posts
</h2>
<h4>
<%= link_to "See Current User's Posts", user_posts_path(current_user) %>
</h4>
<p>
  User Details Below
</p>
  <ul>
    <li>
      <%= link_to "ID: #{current_user.id}", "/users/#{current_user.id}" %>
      <%= link_to "Edit Profile", "/users/#{current_user.id}/edit" %>
      Alias: <%= current_user.alias %>
      Email: <%= current_user.email %>
    </li>
  </ul>
<h4>
<%= link_to "See List of Users", "/users" %>
</h4>